[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-fund --no-audit"
  NODE_OPTIONS = "--max-old-space-size=2048"

# Make sure assets are served directly (and not hijacked by any SPA fallback)
[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200
