# ---------- Build ----------
[build]
  command = "npm ci && npm run build:lifetime"
  publish = "dist/lifetime"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-fund --no-audit"
  NODE_OPTIONS = "--max-old-space-size=2048"

# Serve static assets as files (prevent SPA hijack)
[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200

# Preview-only: keep search engines out
[context."deploy-preview"]
  [[context."deploy-preview".headers]]
    for = "/*"
    [context."deploy-preview".headers.values]
      X-Robots-Tag = "noindex, nofollow"
