[build]
command = "npx @11ty/eleventy --config=eleventy.lifetime.js"
publish = "_site/lifetime"
# Closet Concepts

[build.cc]
command = "npx @11ty/eleventy --config=eleventy.cc.js"
publish = "_site/cc"

# America In-Home
[build.aih]
command = "npx @11ty/eleventy --config=eleventy.aih.js"
publish = "_site/aih"

[dev]
command = "npx @11ty/eleventy --serve --config=eleventy.lifetime.js"
targetPort = 8080
port = 8888
framework = "#custom"
autoLaunch = true

[[redirects]]
from = "/"
to = "/lifetime/"
status = 301

