[build]
command = "npm run build:all && npm run build:root"
publish = "_site"

[dev]
command = "npx @11ty/eleventy --serve --config=eleventy.lifetime.js"
targetPort = 8080
port = 8888
framework = "#custom"
autoLaunch = true

[[redirects]]
from = "/"
to = "/lifetime/"
status = 301

