[build]
  command = "npm run build:all"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/lifetime/:splat"
  status = 200
  conditions = {Role = ["admin"]}

# Serve assets as files, not HTML
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/lifetime/assets/*"
  to = "/lifetime/assets/:splat"
  status = 200

[[redirects]]
  from = "/cc/assets/*"
  to = "/cc/assets/:splat"
  status = 200

[[redirects]]
  from = "/aih/assets/*"
  to = "/aih/assets/:splat"
  status = 200

# Unit-specific routes
[[redirects]]
  from = "/aih/*"
  to = "/aih/:splat"
  status = 200

[[redirects]]
  from = "/cc/*"
  to = "/cc/:splat"
  status = 200

# Default fallback to LHS
[[redirects]]
  from = "/*"
  to = "/lifetime/:splat"
  status = 200
  
[build]
  command = "npm ci && npm run build:all && npm run build:root"
  publish = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-fund --no-audit"
  NODE_OPTIONS = "--max-old-space-size=2048"

# Serve real files before any fallback (multi-page site)
[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200

