[build]
  command = "npm run build:lifetime"
  publish = "dist/lifetime"
  command = "npm run build:aih"
  publish = "dist/aih"
  command = "npm run build:cc"
  publish = "dist/cc"

# Build commands for other brands:
#   npm run build:aih  # outputs to dist/aih
#   npm run build:cc   # outputs to dist/cc
