[build]
command = "npm run build:lifetime && npm run build:aih && npm run build:cc"
publish = "dist"


# Build commands for other brands:
#   npm run build:aih  # outputs to dist/aih
#   npm run build:cc   # outputs to dist/cc
