# ---------- Build ----------
[build]
  # You can keep build:all if you like; build:lifetime is faster
  command = "npm ci && npm run build:lifetime && npm run build:root"
  publish = "dist/lifetime"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-fund --no-audit"
  NODE_OPTIONS = "--max-old-space-size=2048"

# ---------- Preview-only headers ----------
[context."deploy-preview"]
  [[context."deploy-preview".headers]]
    for = "/*"
    [context."deploy-preview".headers.values]
      X-Robots-Tag = "noindex, nofollow"
